spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskList
    username: postgres
    password: 39711
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    enabled: true
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
